### PR TITLE
Create how-to-hire-a-great-developer

### PR DESCRIPTION
**Pull request by chanaphan**

### CODE REVIEW

**Comment by rzhang16** [comment]
Sounds great!

**Comment by chanaphan** [comment]
Thanks :+1:

**Comment by moragots** [comment]
Perfect! :+1: :smile:

**Comment by chanaphan** [comment]
Thanks @jihkim16 @moragots 
@rzhang16 I updated your suggestion in the file. thanks :dancer:

**Comment by jihkim16** [comment]
Perfect

**Pull request merged**
